#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v4
# autospec commit: e738c51
#
Name     : pypi-jupyterlab
Version  : 4.1.3
Release  : 185
URL      : https://files.pythonhosted.org/packages/ce/c1/c6a2e9550236e64983de7d5a5b35510ac45cd836e40ccaa44dce14fec2fe/jupyterlab-4.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/ce/c1/c6a2e9550236e64983de7d5a5b35510ac45cd836e40ccaa44dce14fec2fe/jupyterlab-4.1.3.tar.gz
Summary  : JupyterLab computational environment
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause HPND MIT
Requires: pypi-jupyterlab-bin = %{version}-%{release}
Requires: pypi-jupyterlab-data = %{version}-%{release}
Requires: pypi-jupyterlab-license = %{version}-%{release}
Requires: pypi-jupyterlab-python = %{version}-%{release}
Requires: pypi-jupyterlab-python3 = %{version}-%{release}
Requires: pypi(jupyterlab_server)
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hatchling)
BuildRequires : pypi-jupyter_packaging
BuildRequires : pypi-jupyterlab_server
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
**[Installation](#installation)** |
**[Documentation](https://jupyterlab.readthedocs.io)** |
**[Contributing](#contributing)** |
**[License](#license)** |
**[Team](#team)** |
**[Getting help](#getting-help)** |

%package bin
Summary: bin components for the pypi-jupyterlab package.
Group: Binaries
Requires: pypi-jupyterlab-data = %{version}-%{release}
Requires: pypi-jupyterlab-license = %{version}-%{release}

%description bin
bin components for the pypi-jupyterlab package.


%package data
Summary: data components for the pypi-jupyterlab package.
Group: Data

%description data
data components for the pypi-jupyterlab package.


%package license
Summary: license components for the pypi-jupyterlab package.
Group: Default

%description license
license components for the pypi-jupyterlab package.


%package python
Summary: python components for the pypi-jupyterlab package.
Group: Default
Requires: pypi-jupyterlab-python3 = %{version}-%{release}

%description python
python components for the pypi-jupyterlab package.


%package python3
Summary: python3 components for the pypi-jupyterlab package.
Group: Default
Requires: python3-core
Provides: pypi(jupyterlab)
Requires: pypi(async_lru)
Requires: pypi(httpx)
Requires: pypi(ipykernel)
Requires: pypi(jinja2)
Requires: pypi(jupyter_core)
Requires: pypi(jupyter_lsp)
Requires: pypi(jupyter_server)
Requires: pypi(jupyterlab_server)
Requires: pypi(notebook_shim)
Requires: pypi(packaging)
Requires: pypi(tornado)
Requires: pypi(traitlets)

%description python3
python3 components for the pypi-jupyterlab package.


%prep
%setup -q -n jupyterlab-4.1.3
cd %{_builddir}/jupyterlab-4.1.3
pushd ..
cp -a jupyterlab-4.1.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709596044
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . jupyter-ydoc
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
pypi-dep-fix.py . jupyter-ydoc
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-jupyterlab
cp %{_builddir}/jupyterlab-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jupyterlab/3b9af547018e1ee19a1e4925fd162ff378073ac0 || :
cp %{_builddir}/jupyterlab-%{version}/jupyterlab/static/1036.0d1f109c3d842497fd51.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-jupyterlab/01ebbe688c25d738b9ee0e2de8113f7351c88e7a || :
cp %{_builddir}/jupyterlab-%{version}/jupyterlab/static/627.7e292370f4d61d9e8648.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-jupyterlab/cd522246a57b87ba54b1b6b92174b9091f70e983 || :
cp %{_builddir}/jupyterlab-%{version}/jupyterlab/static/7451.c0257dbfdd320e2c21f5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-jupyterlab/84edab031b618e7ed5e6e4b764e1877913d64820 || :
cp %{_builddir}/jupyterlab-%{version}/jupyterlab/static/9826.406d2a71dc45995bc549.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-jupyterlab/b8340cc7166c3efc8fa891de21b9b52fd70151cb || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
pypi-dep-fix.py %{buildroot} jupyter-ydoc
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
## install_append content
mkdir -p  %{buildroot}/usr/share/jupyter/
mv %{buildroot}/usr/etc/jupyter/jupyter_notebook_config.d %{buildroot}/usr/share/jupyter/
mv %{buildroot}/usr/etc/jupyter/jupyter_server_config.d/jupyterlab.json  %{buildroot}/usr/share/jupyter/
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jlpm
/usr/bin/jupyter-lab
/usr/bin/jupyter-labextension
/usr/bin/jupyter-labhub

%files data
%defattr(-,root,root,-)
/usr/share/applications/jupyterlab.desktop
/usr/share/icons/hicolor/scalable/apps/jupyterlab.svg
/usr/share/jupyter/jupyter_notebook_config.d/jupyterlab.json
/usr/share/jupyter/jupyterlab.json
/usr/share/jupyter/lab/schemas/@jupyterlab/application-extension/commands.json
/usr/share/jupyter/lab/schemas/@jupyterlab/application-extension/context-menu.json
/usr/share/jupyter/lab/schemas/@jupyterlab/application-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/application-extension/property-inspector.json
/usr/share/jupyter/lab/schemas/@jupyterlab/application-extension/shell.json
/usr/share/jupyter/lab/schemas/@jupyterlab/application-extension/top-bar.json
/usr/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/notification.json
/usr/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/palette.json
/usr/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/print.json
/usr/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/sanitizer.json
/usr/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/themes.json
/usr/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/utilityCommands.json
/usr/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/workspaces.json
/usr/share/jupyter/lab/schemas/@jupyterlab/cell-toolbar-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/cell-toolbar-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/celltags-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/celltags-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/codemirror-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/codemirror-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/completer-extension/inline-completer.json
/usr/share/jupyter/lab/schemas/@jupyterlab/completer-extension/manager.json
/usr/share/jupyter/lab/schemas/@jupyterlab/completer-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/console-extension/completer.json
/usr/share/jupyter/lab/schemas/@jupyterlab/console-extension/foreign.json
/usr/share/jupyter/lab/schemas/@jupyterlab/console-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/console-extension/tracker.json
/usr/share/jupyter/lab/schemas/@jupyterlab/csvviewer-extension/csv.json
/usr/share/jupyter/lab/schemas/@jupyterlab/csvviewer-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/csvviewer-extension/tsv.json
/usr/share/jupyter/lab/schemas/@jupyterlab/debugger-extension/main.json
/usr/share/jupyter/lab/schemas/@jupyterlab/debugger-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/docmanager-extension/download.json
/usr/share/jupyter/lab/schemas/@jupyterlab/docmanager-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/docmanager-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/documentsearch-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/documentsearch-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/extensionmanager-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/extensionmanager-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/browser.json
/usr/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/download.json
/usr/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/open-browser-tab.json
/usr/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/open-with.json
/usr/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/filebrowser-extension/widget.json
/usr/share/jupyter/lab/schemas/@jupyterlab/fileeditor-extension/completer.json
/usr/share/jupyter/lab/schemas/@jupyterlab/fileeditor-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/fileeditor-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/help-extension/about.json
/usr/share/jupyter/lab/schemas/@jupyterlab/help-extension/jupyter-forum.json
/usr/share/jupyter/lab/schemas/@jupyterlab/help-extension/launch-classic.json
/usr/share/jupyter/lab/schemas/@jupyterlab/help-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/htmlviewer-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/htmlviewer-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/hub-extension/menu.json
/usr/share/jupyter/lab/schemas/@jupyterlab/hub-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/imageviewer-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/imageviewer-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/inspector-extension/consoles.json
/usr/share/jupyter/lab/schemas/@jupyterlab/inspector-extension/inspector.json
/usr/share/jupyter/lab/schemas/@jupyterlab/inspector-extension/notebooks.json
/usr/share/jupyter/lab/schemas/@jupyterlab/inspector-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/launcher-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/launcher-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/logconsole-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/logconsole-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/lsp-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/lsp-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/mainmenu-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/mainmenu-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/markdownviewer-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/markdownviewer-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/mathjax-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/mathjax-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/metadataform-extension/metadataforms.json
/usr/share/jupyter/lab/schemas/@jupyterlab/metadataform-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/completer.json
/usr/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/export.json
/usr/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/panel.json
/usr/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/tools.json
/usr/share/jupyter/lab/schemas/@jupyterlab/notebook-extension/tracker.json
/usr/share/jupyter/lab/schemas/@jupyterlab/running-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/running-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/settingeditor-extension/form-ui.json
/usr/share/jupyter/lab/schemas/@jupyterlab/settingeditor-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/settingeditor-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/shortcuts-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/shortcuts-extension/shortcuts.json
/usr/share/jupyter/lab/schemas/@jupyterlab/statusbar-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/statusbar-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/terminal-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/terminal-extension/plugin.json
/usr/share/jupyter/lab/schemas/@jupyterlab/toc-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/toc-extension/registry.json
/usr/share/jupyter/lab/schemas/@jupyterlab/tooltip-extension/consoles.json
/usr/share/jupyter/lab/schemas/@jupyterlab/tooltip-extension/files.json
/usr/share/jupyter/lab/schemas/@jupyterlab/tooltip-extension/notebooks.json
/usr/share/jupyter/lab/schemas/@jupyterlab/tooltip-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/translation-extension/package.json.orig
/usr/share/jupyter/lab/schemas/@jupyterlab/translation-extension/plugin.json
/usr/share/jupyter/lab/static/1036.0d1f109c3d842497fd51.js
/usr/share/jupyter/lab/static/1036.0d1f109c3d842497fd51.js.LICENSE.txt
/usr/share/jupyter/lab/static/1085.0b67f0736d85ec41fdd4.js
/usr/share/jupyter/lab/static/1142.d5442a459b18907c1f91.js
/usr/share/jupyter/lab/static/1166.08f9e1fd722f61c9b69c.js
/usr/share/jupyter/lab/static/1168.0a95b9c93afe61ceb527.js
/usr/share/jupyter/lab/static/1294.9d27be1098bc8abebe3f.js
/usr/share/jupyter/lab/static/1410.e2302ff5f564d6e596bb.js
/usr/share/jupyter/lab/static/1420.e8486ed074346bc629ca.js
/usr/share/jupyter/lab/static/1448.c391061d8a8344f9d177.js
/usr/share/jupyter/lab/static/1452.4cc17f31511d1f9c6052.js
/usr/share/jupyter/lab/static/1467.dcd89539f6477c1367af.js
/usr/share/jupyter/lab/static/1550.09375e869bc25429b07a.js
/usr/share/jupyter/lab/static/1581.e988a625b879002dcc04.js
/usr/share/jupyter/lab/static/1581.e988a625b879002dcc04.js.LICENSE.txt
/usr/share/jupyter/lab/static/1608.61240f3db67d3d952790.js
/usr/share/jupyter/lab/static/1716.a6bbe1ae8a1986a73623.js
/usr/share/jupyter/lab/static/1760.9a71f4501e9bbaa4c4d8.js
/usr/share/jupyter/lab/static/1776.4f9305d35480467b23c9.js
/usr/share/jupyter/lab/static/1861.4fc7b4afe2b09eb6b5c0.js
/usr/share/jupyter/lab/static/1903.3b452e8ec30e57dbaba5.js
/usr/share/jupyter/lab/static/1917.05d73322caab1f77e3bf.js
/usr/share/jupyter/lab/static/1929.96e62233aa6f2a8363d4.js
/usr/share/jupyter/lab/static/1945.0fbbfe93a4aedd91875c.js
/usr/share/jupyter/lab/static/1954.07d96e4020ed6e543d25.js
/usr/share/jupyter/lab/static/1993.f8c5682f95ffa75cbaf6.js
/usr/share/jupyter/lab/static/1cb1c39ea642f26a4dfe.woff
/usr/share/jupyter/lab/static/2039.aa079dac5c520f93b234.js
/usr/share/jupyter/lab/static/2090.abc86741318f76c3d726.js
/usr/share/jupyter/lab/static/2091.600b1c32af186f6405f9.js
/usr/share/jupyter/lab/static/2104.296346db0067b4883fbf.js
/usr/share/jupyter/lab/static/2145.be9ec610f29703694fcf.js
/usr/share/jupyter/lab/static/2254.55c69210925ec9b28dd9.js
/usr/share/jupyter/lab/static/226.5dc3528c008170b37b21.js
/usr/share/jupyter/lab/static/2295.cda0f7182bf2a1a03c5a.js
/usr/share/jupyter/lab/static/2320.04abae549b19363c2fdd.js
/usr/share/jupyter/lab/static/2363.6eef078cb37c32d7fbc3.js
/usr/share/jupyter/lab/static/2459.9f9cb02561de1bec73ff.js
/usr/share/jupyter/lab/static/2485.dab750ed66209df61fe1.js
/usr/share/jupyter/lab/static/2551.b07d561a12360c38c589.js
/usr/share/jupyter/lab/static/2579.b19edefeb9ee4daed4bd.js
/usr/share/jupyter/lab/static/2617.9c299e26785f7646cb39.js
/usr/share/jupyter/lab/static/2646.0864fb63d7ab1ed16893.js
/usr/share/jupyter/lab/static/2655.71a94960aa4ab2040d8f.js
/usr/share/jupyter/lab/static/26683bf201fb258a2237.woff
/usr/share/jupyter/lab/static/2727.6925b8cf1c5363f40138.js
/usr/share/jupyter/lab/static/2755.696bab6bdca0d9a78131.js
/usr/share/jupyter/lab/static/2800.680b1fa0a4c66c69bb1e.js
/usr/share/jupyter/lab/static/2857.27a6e85f5c4c092ab8a2.js
/usr/share/jupyter/lab/static/2909.e190307f7f84c7691068.js
/usr/share/jupyter/lab/static/292.3f7844a129f16ec1ffbc.js
/usr/share/jupyter/lab/static/2929.b88233153dbf33f40b29.js
/usr/share/jupyter/lab/static/2953.92ff8f12bad6ee06859c.js
/usr/share/jupyter/lab/static/2990.ea15322a41d3f133989b.js
/usr/share/jupyter/lab/static/2995.0448b3ed572d9cc5fcc7.js
/usr/share/jupyter/lab/static/3056.8a73f6aacd8ca45f84f9.js
/usr/share/jupyter/lab/static/30e889b58cbc51adfbb0.woff
/usr/share/jupyter/lab/static/3123.85cea4be2e2ed3f9654f.js
/usr/share/jupyter/lab/static/32792104b5ef69eded90.woff
/usr/share/jupyter/lab/static/3306.8bdc49ad1a7ca593a838.js
/usr/share/jupyter/lab/static/3308.764d71af7e591cdb1345.js
/usr/share/jupyter/lab/static/3520.3495b98946de6960ace8.js
/usr/share/jupyter/lab/static/3528.3b5ef5f31d460b5fcd01.js
/usr/share/jupyter/lab/static/3547.bd90e90bfe79911486e8.js
/usr/share/jupyter/lab/static/3549.24f2fe646d8128bc9db0.js
/usr/share/jupyter/lab/static/355254db9ca10a09a3b5.woff
/usr/share/jupyter/lab/static/3601.5c17c015d71b69ddcab3.js
/usr/share/jupyter/lab/static/36e0d72d8a7afc696a3e.woff
/usr/share/jupyter/lab/static/3711.150292a21fd47be1c05f.js
/usr/share/jupyter/lab/static/3724.a4657dc16be2ffc49282.js
/usr/share/jupyter/lab/static/373c04fd2418f5c77eea.eot
/usr/share/jupyter/lab/static/378.6d0f0fc4c8a2eb80ac43.js
/usr/share/jupyter/lab/static/3783.93d5366ab28a19e1f0f9.js
/usr/share/jupyter/lab/static/3807.08a8fd824036c30b3746.js
/usr/share/jupyter/lab/static/383.db345dbeef5ef774e50c.js
/usr/share/jupyter/lab/static/3871.ba96e5b53bb16df56618.js
/usr/share/jupyter/lab/static/3923.f29c06abdcb560130471.js
/usr/share/jupyter/lab/static/3935.905285b8e22c337968ed.js
/usr/share/jupyter/lab/static/3935.905285b8e22c337968ed.js.LICENSE.txt
/usr/share/jupyter/lab/static/3962.50786e3ed9a01329a4a0.js
/usr/share/jupyter/lab/static/3bc6ecaae7ecf6f8d7f8.woff
/usr/share/jupyter/lab/static/3de784d07b9fa8f104c1.woff
/usr/share/jupyter/lab/static/3f6d3488cf65374f6f67.woff
/usr/share/jupyter/lab/static/4008.86acbefff6de679f77b5.js
/usr/share/jupyter/lab/static/4008.86acbefff6de679f77b5.js.LICENSE.txt
/usr/share/jupyter/lab/static/4017.096a74a538e031b6d346.js
/usr/share/jupyter/lab/static/4043.aa012978c41d1d1b2f14.js
/usr/share/jupyter/lab/static/406.81906f96059e31e907a2.js
/usr/share/jupyter/lab/static/4086.3087c0abed5ca45b823b.js
/usr/share/jupyter/lab/static/4136.4b9f72f85f49f979ebb8.js
/usr/share/jupyter/lab/static/4136.4b9f72f85f49f979ebb8.js.LICENSE.txt
/usr/share/jupyter/lab/static/4139.303ee7374c742287be85.js
/usr/share/jupyter/lab/static/4155.5a8d6736017097028d78.js
/usr/share/jupyter/lab/static/4283.f6092d8b7f2e53118d1b.js
/usr/share/jupyter/lab/static/4291.e5d8997127541f75fdaf.js
/usr/share/jupyter/lab/static/4405.43dab120fea32f30bbb9.js
/usr/share/jupyter/lab/static/4419.93938494f456cd76a7e3.js
/usr/share/jupyter/lab/static/4452.2f8819684b96ecff5231.js
/usr/share/jupyter/lab/static/4519.6b784d052db42e93eff2.js
/usr/share/jupyter/lab/static/4562.72444a09f5f092646490.js
/usr/share/jupyter/lab/static/4591.428531724f49fe824ffa.js
/usr/share/jupyter/lab/static/46.fb119c5e5b1e0c72a00f.js
/usr/share/jupyter/lab/static/4743.d4e9658ea25301e15a94.js
/usr/share/jupyter/lab/static/4765.093b4f8b3cee1251db8d.js
/usr/share/jupyter/lab/static/481e39042508ae313a60.woff
/usr/share/jupyter/lab/static/4878.73004381601237a3ef9c.js
/usr/share/jupyter/lab/static/49.7233f68f95d10b85a83e.js
/usr/share/jupyter/lab/static/4986.a497cdda4b7152902568.js
/usr/share/jupyter/lab/static/5041.cdc120bda0a0dec4cfc2.js
/usr/share/jupyter/lab/static/5157.9c77dc27a251d4135876.js
/usr/share/jupyter/lab/static/5201.8866042bae350659528a.js
/usr/share/jupyter/lab/static/5203.c002d40ac647dc6e1d61.js
/usr/share/jupyter/lab/static/526.601d8ddd8347cd7790b9.js
/usr/share/jupyter/lab/static/5331.0cd3f010bb08983ec3fd.js
/usr/share/jupyter/lab/static/5440.2541fcda12b661665148.js
/usr/share/jupyter/lab/static/5521.ce4a0274596e0325374c.js
/usr/share/jupyter/lab/static/5746.e4434ef2027bcc5ed0c9.js
/usr/share/jupyter/lab/static/5794.3cb2bcd1a3e23d0c084e.js
/usr/share/jupyter/lab/static/581.2b878ed37172aced15b5.js
/usr/share/jupyter/lab/static/5881.3946238aa4afdcf4f964.js
/usr/share/jupyter/lab/static/5959.a6b1fd3b03d3649ea8b1.js
/usr/share/jupyter/lab/static/5cda41563a095bd70c78.woff
/usr/share/jupyter/lab/static/6001.963601fcecb8b4c1d1f1.js
/usr/share/jupyter/lab/static/6059.d83e7323b2ee1aa16009.js
/usr/share/jupyter/lab/static/6163.f5b51a9f0df4846ba40f.js
/usr/share/jupyter/lab/static/6207.a8079c8d8a61039dd530.js
/usr/share/jupyter/lab/static/6243.2efd673d1304c43b7b78.js
/usr/share/jupyter/lab/static/6267.1def2916929e185ab9fc.js
/usr/share/jupyter/lab/static/627.7e292370f4d61d9e8648.js
/usr/share/jupyter/lab/static/627.7e292370f4d61d9e8648.js.LICENSE.txt
/usr/share/jupyter/lab/static/6359.4b994bfd6b1dea2d6fe3.js
/usr/share/jupyter/lab/static/6436.8d9ba427de4ab1053871.js
/usr/share/jupyter/lab/static/6443.e6b52d3732b3e8513a71.js
/usr/share/jupyter/lab/static/6515.56c63929fb079a820cbc.js
/usr/share/jupyter/lab/static/6532.bb7137729a2d6d4e6ddf.js
/usr/share/jupyter/lab/static/6560.f42276a0b1b92aea515b.js
/usr/share/jupyter/lab/static/6595.6a1d7e1abbf186dd119b.js
/usr/share/jupyter/lab/static/6686.3c518aa6e5f9785fb486.js
/usr/share/jupyter/lab/static/6770.fd7084bb2f4b7622401d.js
/usr/share/jupyter/lab/static/6778.345e6ac9818e30317310.js
/usr/share/jupyter/lab/static/6815.0b699f0c162a24b0dbe3.js
/usr/share/jupyter/lab/static/6888.9d3914817f3290827a64.js
/usr/share/jupyter/lab/static/6898.742a7062fa979fb68a80.js
/usr/share/jupyter/lab/static/7080.1330328bb6f46b4da81e.js
/usr/share/jupyter/lab/static/7112.d5120c85ebd17620dda0.js
/usr/share/jupyter/lab/static/7161.353c3ab960df72e6f1ea.js
/usr/share/jupyter/lab/static/7173.e28f63dbd553818e07d3.js
/usr/share/jupyter/lab/static/7178.5f3dd740449b44efad2d.js
/usr/share/jupyter/lab/static/7178.5f3dd740449b44efad2d.js.LICENSE.txt
/usr/share/jupyter/lab/static/721921bab0d001ebff02.woff
/usr/share/jupyter/lab/static/7245.c0cae8787dcd00b991b7.js
/usr/share/jupyter/lab/static/7272.72081c10e0f645b0631a.js
/usr/share/jupyter/lab/static/7294.badf85a3180703d63f62.js
/usr/share/jupyter/lab/static/7294.badf85a3180703d63f62.js.LICENSE.txt
/usr/share/jupyter/lab/static/72bc573386dd1d48c5bb.woff
/usr/share/jupyter/lab/static/7313.4a8a9a1eee6f7ef15ee1.js
/usr/share/jupyter/lab/static/7313.4a8a9a1eee6f7ef15ee1.js.LICENSE.txt
/usr/share/jupyter/lab/static/7317.af8a7da0f881a22752c1.js
/usr/share/jupyter/lab/static/7318.397bf8e913e825b2be27.js
/usr/share/jupyter/lab/static/7363.abe8e31a91e113753bae.js
/usr/share/jupyter/lab/static/7384.60351e008d8f687e8fcc.js
/usr/share/jupyter/lab/static/7390.8253478b90f756692702.js
/usr/share/jupyter/lab/static/7418.a8a30214fd61cb7133a5.js
/usr/share/jupyter/lab/static/7426.c83966ccc62601d391bd.js
/usr/share/jupyter/lab/static/7426.c83966ccc62601d391bd.js.LICENSE.txt
/usr/share/jupyter/lab/static/745.85516a9bb83bcd94d00d.js
/usr/share/jupyter/lab/static/7451.c0257dbfdd320e2c21f5.js
/usr/share/jupyter/lab/static/7451.c0257dbfdd320e2c21f5.js.LICENSE.txt
/usr/share/jupyter/lab/static/7472.58ba8647a489d019c2ef.js
/usr/share/jupyter/lab/static/7473.5012397d10d3b945ecaa.js
/usr/share/jupyter/lab/static/7508.b902347f820c70cd386a.js
/usr/share/jupyter/lab/static/7511.b381a696cf806983c654.js
/usr/share/jupyter/lab/static/7517.f3e5d420f4af90d442dd.js
/usr/share/jupyter/lab/static/7629.1f295461ebf56a48c197.js
/usr/share/jupyter/lab/static/7669.343e259c4c8269479f5b.js
/usr/share/jupyter/lab/static/7702.c479c69f7a532f7b3fd5.js
/usr/share/jupyter/lab/static/7730.7e3a9fb140d2d55a51fc.js
/usr/share/jupyter/lab/static/7731.26db150e967313b7a7e2.js
/usr/share/jupyter/lab/static/7734.b08c15e9f538f44d0f52.js
/usr/share/jupyter/lab/static/7763.19a095394000f9ef62bd.js
/usr/share/jupyter/lab/static/7763.19a095394000f9ef62bd.js.LICENSE.txt
/usr/share/jupyter/lab/static/7775.3e0dee729369fe3d5008.js
/usr/share/jupyter/lab/static/7823.817687f13e9a6781fdd3.js
/usr/share/jupyter/lab/static/7827.e36d073d947bf02a05e3.js
/usr/share/jupyter/lab/static/7848.e83aa4b90ae87209abb8.js
/usr/share/jupyter/lab/static/786.8a99ee7dbd7bd0eb9dce.js
/usr/share/jupyter/lab/static/7877.a4c46a784149533b91d4.js
/usr/share/jupyter/lab/static/7887.128a155df5d25e88c0ce.js
/usr/share/jupyter/lab/static/7946.7fe46d47492e459b7cb5.js
/usr/share/jupyter/lab/static/795.47ab66037ef33f808f09.js
/usr/share/jupyter/lab/static/79d088064beb3826054f.eot
/usr/share/jupyter/lab/static/8002.25f64485372af5158c83.js
/usr/share/jupyter/lab/static/8010.1cf8237e9def8404f355.js
/usr/share/jupyter/lab/static/8012.40cb006f0c180ebafa91.js
/usr/share/jupyter/lab/static/812.26751e6a48790ef27567.js
/usr/share/jupyter/lab/static/8152.5baac73844a065f34284.js
/usr/share/jupyter/lab/static/8285.1eac7b7582569be1c3a8.js
/usr/share/jupyter/lab/static/8302.5c5e5a2da7fe74b12a1d.js
/usr/share/jupyter/lab/static/8319.80fcbc832e1eb20b71e7.js
/usr/share/jupyter/lab/static/8322.288af285dac9cb9a8800.js
/usr/share/jupyter/lab/static/8347.573b699e3590729bfa8a.js
/usr/share/jupyter/lab/static/8405.154ba4b17a2dec22a355.js
/usr/share/jupyter/lab/static/8462.74d5f5afd4f9d7825eed.js
/usr/share/jupyter/lab/static/8493.fc635229db38e6fc6aa2.js
/usr/share/jupyter/lab/static/8498.27a245b23921914bf5c2.js
/usr/share/jupyter/lab/static/8512.574af1cce4d4d2af5239.js
/usr/share/jupyter/lab/static/8678.dcd3dab9025b13eb9be8.js
/usr/share/jupyter/lab/static/870673df72e70f87c91a.woff
/usr/share/jupyter/lab/static/8710.5fc5ecb762fb4494db02.js
/usr/share/jupyter/lab/static/8738.782816e9072ac38762b4.js
/usr/share/jupyter/lab/static/8771.327a202178f82f3b15b8.js
/usr/share/jupyter/lab/static/8787.4d36d28dcf94bf59cbfe.js
/usr/share/jupyter/lab/static/8805.0f14a91b024b59c039a7.js
/usr/share/jupyter/lab/static/881.972f79365eed0f77378e.js
/usr/share/jupyter/lab/static/8823.2ff947bcd96cc0723058.js
/usr/share/jupyter/lab/static/8875.88988caaba1e33edad5b.js
/usr/share/jupyter/lab/static/88b98cad3688915e50da.woff
/usr/share/jupyter/lab/static/8ea8791754915a898a31.woff2
/usr/share/jupyter/lab/static/8ea8dbb1b02e6f730f55.woff
/usr/share/jupyter/lab/static/9.0e0cba0ccc2a4b670600.js
/usr/share/jupyter/lab/static/9030.260bc05e28eccff70ae8.js
/usr/share/jupyter/lab/static/9041.df39043656c7233552e4.js
/usr/share/jupyter/lab/static/9055.bd710a8db8883a836b59.js
/usr/share/jupyter/lab/static/9109.fa3ee74a5c0f378f4d51.js
/usr/share/jupyter/lab/static/9192.db4337a516b7f38d1f89.js
/usr/share/jupyter/lab/static/9222.1c2a8e69a2de57dd1984.js
/usr/share/jupyter/lab/static/9230.58b8c42b730e1a56e69b.js
/usr/share/jupyter/lab/static/9265.bc2b66a4502cdfcfc14f.js
/usr/share/jupyter/lab/static/9362.823dcfac216f8057452d.js
/usr/share/jupyter/lab/static/9395.b59dceae72715c9f885c.js
/usr/share/jupyter/lab/static/9409.34c33ed11e2d6f318480.js
/usr/share/jupyter/lab/static/942.93c8de61ea9ea08ec097.js
/usr/share/jupyter/lab/static/9421.022dc7b4e9a2c80c32c2.js
/usr/share/jupyter/lab/static/9440.04751e25c9cde059ff37.js
/usr/share/jupyter/lab/static/9445.fe5e9e5b728de8d15873.js
/usr/share/jupyter/lab/static/9545.f0f7a2959bdd17ee3448.js
/usr/share/jupyter/lab/static/9579.4b1b079b6b7cd2924338.js
/usr/share/jupyter/lab/static/9579.4b1b079b6b7cd2924338.js.LICENSE.txt
/usr/share/jupyter/lab/static/9621.9cbfa52c42927bb398b4.js
/usr/share/jupyter/lab/static/9653.d93c93e084cd5e93cd2d.js
/usr/share/jupyter/lab/static/9674eb1bd55047179038.svg
/usr/share/jupyter/lab/static/9738.c0234a1f7f6ac262f560.js
/usr/share/jupyter/lab/static/9747.6dd327f4928c6989ea8a.js
/usr/share/jupyter/lab/static/9747.6dd327f4928c6989ea8a.js.LICENSE.txt
/usr/share/jupyter/lab/static/9826.406d2a71dc45995bc549.js
/usr/share/jupyter/lab/static/9826.406d2a71dc45995bc549.js.LICENSE.txt
/usr/share/jupyter/lab/static/9834b82ad26e2a37583d.woff2
/usr/share/jupyter/lab/static/9870.70b2b59cc96c3a97c489.js
/usr/share/jupyter/lab/static/9984.6ba5355e0d5487d5ac63.js
/usr/share/jupyter/lab/static/a009bea404f7a500ded4.woff
/usr/share/jupyter/lab/static/a3b9817780214caf01e8.svg
/usr/share/jupyter/lab/static/af04542b29eaac04550a.woff
/usr/share/jupyter/lab/static/af6397503fcefbd61397.ttf
/usr/share/jupyter/lab/static/af96f67d7accf5fd2a4a.woff
/usr/share/jupyter/lab/static/b418136e3b384baaadec.woff
/usr/share/jupyter/lab/static/be0a084962d8066884f7.svg
/usr/share/jupyter/lab/static/bootstrap.js
/usr/share/jupyter/lab/static/build_log.json
/usr/share/jupyter/lab/static/c49810b53ecc0d87d802.woff
/usr/share/jupyter/lab/static/c56da8d69f1a0208b8e0.woff
/usr/share/jupyter/lab/static/cb9e9e693192413cde2b.woff
/usr/share/jupyter/lab/static/cda59d6efffa685830fd.ttf
/usr/share/jupyter/lab/static/e4299464e7b012968eed.eot
/usr/share/jupyter/lab/static/e42a88444448ac3d6054.woff2
/usr/share/jupyter/lab/static/e8711bbb871afd8e9dea.ttf
/usr/share/jupyter/lab/static/f9217f66874b0c01cd8c.woff
/usr/share/jupyter/lab/static/fc6ddf5df402b263cfb1.woff
/usr/share/jupyter/lab/static/index.html
/usr/share/jupyter/lab/static/index.out.js
/usr/share/jupyter/lab/static/jlab_core.91d505dd572f3f14e6ac.js
/usr/share/jupyter/lab/static/main.cea49ccbbe07d3cabe73.js
/usr/share/jupyter/lab/static/package.json
/usr/share/jupyter/lab/static/style.js
/usr/share/jupyter/lab/static/third-party-licenses.json
/usr/share/jupyter/lab/themes/@jupyterlab/theme-dark-extension/index.css
/usr/share/jupyter/lab/themes/@jupyterlab/theme-dark-extension/index.js
/usr/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css
/usr/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.js

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-jupyterlab/01ebbe688c25d738b9ee0e2de8113f7351c88e7a
/usr/share/package-licenses/pypi-jupyterlab/3b9af547018e1ee19a1e4925fd162ff378073ac0
/usr/share/package-licenses/pypi-jupyterlab/84edab031b618e7ed5e6e4b764e1877913d64820
/usr/share/package-licenses/pypi-jupyterlab/b8340cc7166c3efc8fa891de21b9b52fd70151cb
/usr/share/package-licenses/pypi-jupyterlab/cd522246a57b87ba54b1b6b92174b9091f70e983

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
